<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DDT_Cura_login_002_validation_TestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>acb3861f-e83e-4a5e-a9f0-1bb1bc2c3a09</testSuiteGuid>
   <testCaseLink>
      <guid>01d7816c-6f93-44b5-bbfd-87747488169c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DDT/TC_Cura_Home_Login_002</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e6013fa1-43bd-485d-abf9-6a46a994b98b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Cura_TestData/Cura_TestData_Excel_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e6013fa1-43bd-485d-abf9-6a46a994b98b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UserName</value>
         <variableId>c2da5049-bae3-4051-a501-add501a24f88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e6013fa1-43bd-485d-abf9-6a46a994b98b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>5660f887-2aaf-45c3-b775-534526240f96</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
